# lincao_dict.py
# 🤖 自动生成的林草大模型全要素语义与精度字典 (105 个真实字段精确对齐版)

# =====================================================================
# 1. 物理真值精度底座 (FIELD_METADATA) - 共 105 个核心业务字段
# =====================================================================
FIELD_METADATA = {
    "SHENG": {"chinese_name": "省代码", "decimals": 0},
    "XIAN": {"chinese_name": "县代码", "decimals": 0},
    "XIANG": {"chinese_name": "乡代码", "decimals": 0},
    "CUN": {"chinese_name": "村代码", "decimals": 0},
    "LIN_YE_JU": {"chinese_name": "林业局(牧场)", "decimals": 0},
    "LIN_CHANG": {"chinese_name": "林场(分场)", "decimals": 0},
    "LIN_BAN": {"chinese_name": "林(草)班", "decimals": 0},
    "XIAO_BAN": {"chinese_name": "小班号", "decimals": 0},
    "XBMJ": {"chinese_name": "小班面积", "decimals": 2},
    "ZB_JG": {"chinese_name": "植被结构", "decimals": 0},
    "DI_LEI": {"chinese_name": "地类", "decimals": 0},
    "KZLLHTD": {"chinese_name": "可造林绿化土地", "decimals": 0},
    "DCQLX": {"chinese_name": "荒漠调查区类型", "decimals": 0},
    "STQW": {"chinese_name": "生态区位", "decimals": 0},
    "STQWMC": {"chinese_name": "生态区位名称", "decimals": 0},
    "DI_MAO": {"chinese_name": "地貌", "decimals": 0},
    "HAI_BA": {"chinese_name": "海拔", "decimals": 0},
    "PO_XIANG": {"chinese_name": "坡向", "decimals": 0},
    "PO_WEI": {"chinese_name": "坡位", "decimals": 0},
    "PO_DU": {"chinese_name": "坡度", "decimals": 0},
    "TU_RANG_LX": {"chinese_name": "土壤类型", "decimals": 0},
    "TU_CENG_HD": {"chinese_name": "土层厚度", "decimals": 0},
    "TU_RANG_ZD": {"chinese_name": "土壤质地", "decimals": 0},
    "LD_QS": {"chinese_name": "土地所有权属", "decimals": 0},
    "TDSYQS": {"chinese_name": "土地使用权属", "decimals": 0},
    "ZBFGLX": {"chinese_name": "植被覆盖类型", "decimals": 0},
    "YOU_SHI_SZ": {"chinese_name": "优势树(草)种", "decimals": 0},
    "YU_BI_DU": {"chinese_name": "郁闭度", "decimals": 2},
    "GMGD": {"chinese_name": "灌木盖度", "decimals": 0},
    "CBGD": {"chinese_name": "草本盖度", "decimals": 0},
    "ZBGD": {"chinese_name": "植被总盖度", "decimals": 0},
    "BY1": {"chinese_name": "备用字段1", "decimals": 0},
    "BY2": {"chinese_name": "备用字段2", "decimals": 0},
    "BY3": {"chinese_name": "备用字段3", "decimals": 0},
    "BY4": {"chinese_name": "备用字段4", "decimals": 0},
    "BY5": {"chinese_name": "备用字段5", "decimals": 0},
    "LDGL_LX": {"chinese_name": "林地管理类型", "decimals": 0},
    "BH_DJ": {"chinese_name": "林地保护等级", "decimals": 0},
    "LMQS": {"chinese_name": "林木所有权属", "decimals": 0},
    "LMSYQS": {"chinese_name": "林木使用权属", "decimals": 0},
    "LIN_ZHONG": {"chinese_name": "林种", "decimals": 0},
    "SHI_QUAN_D": {"chinese_name": "事权等级", "decimals": 0},
    "QI_YUAN": {"chinese_name": "起源", "decimals": 0},
    "LING_ZU": {"chinese_name": "龄组", "decimals": 0},
    "PINGJUN_XJ": {"chinese_name": "平均胸径", "decimals": 1},
    "PINGJUN_SG": {"chinese_name": "平均树高", "decimals": 1},
    "MEI_GQ_ZS": {"chinese_name": "每公顷株数", "decimals": 0},
    "MEI_GQ_XJ": {"chinese_name": "每公顷蓄积", "decimals": 2},
    "PINGJUN_NL": {"chinese_name": "平均年龄", "decimals": 0},
    "SHUZHONG_ZC": {"chinese_name": "树种组成", "decimals": 0},
    "ZL_DJ": {"chinese_name": "林地质量等级", "decimals": 0},
    "CY_FQ": {"chinese_name": "草原分区", "decimals": 0},
    "CDGL_LX": {"chinese_name": "草原管理类型", "decimals": 0},
    "CYLB": {"chinese_name": "草原类别", "decimals": 0},
    "CD_QY": {"chinese_name": "草原起源", "decimals": 0},
    "CD_L": {"chinese_name": "草原类", "decimals": 0},
    "CD_XING": {"chinese_name": "草原型", "decimals": 0},
    "YS_CAOZ": {"chinese_name": "优势草种", "decimals": 0},
    "CDGN": {"chinese_name": "功能类别", "decimals": 0},
    "CDLYFS": {"chinese_name": "草原利用方式", "decimals": 0},
    "FM_SHCH": {"chinese_name": "放牧时长", "decimals": 0},
    "LBMJ_BL": {"chinese_name": "裸斑面积比例", "decimals": 0},
    "THLX": {"chinese_name": "草原退化类型", "decimals": 0},
    "THCD": {"chinese_name": "草原退化程度", "decimals": 0},
    "JM_PH": {"chinese_name": "禁牧与草畜平衡", "decimals": 0},
    "JKDJ": {"chinese_name": "草原健康等级", "decimals": 0},
    "SDGLLX": {"chinese_name": "湿地管理类型", "decimals": 0},
    "SD_DJ": {"chinese_name": "湿地管理分级", "decimals": 0},
    "ZYSD_BM": {"chinese_name": "重要湿地名称", "decimals": 0},
    "BHDLX": {"chinese_name": "自然保护地类型", "decimals": 0},
    "BHDBM": {"chinese_name": "自然保护地名称", "decimals": 0},
    "SDLYFS": {"chinese_name": "湿地利用方式", "decimals": 0},
    "SDWXZK": {"chinese_name": "受威胁状况", "decimals": 0},
    "QHLX": {"chinese_name": "气候类型", "decimals": 0},
    "SHLX": {"chinese_name": "沙化类型", "decimals": 0},
    "SHCD": {"chinese_name": "沙化程度", "decimals": 0},
    "SSSMSD": {"chinese_name": "所属沙漠沙地", "decimals": 0},
    "HMHLX": {"chinese_name": "荒漠化类型", "decimals": 0},
    "HMHCD": {"chinese_name": "荒漠化程度", "decimals": 0},
    "TRLS": {"chinese_name": "基岩裸露度/土壤砾石含量", "decimals": 1},
    "FSHD": {"chinese_name": "覆沙厚度", "decimals": 1},
    "SQGD": {"chinese_name": "沙丘高度", "decimals": 1},
    "QSG": {"chinese_name": "侵蚀沟面积比例", "decimals": 1},
    "YJB": {"chinese_name": "盐碱斑占地率", "decimals": 1},
    "ZWCLXJL": {"chinese_name": "作物产量下降率", "decimals": 1},
    "ZWQML": {"chinese_name": "作物缺苗率", "decimals": 1},
    "ZWCL": {"chinese_name": "作物产量", "decimals": 1},
    "GGNL": {"chinese_name": "灌溉能力", "decimals": 0},
    "NTLWHL": {"chinese_name": "农田林网化率", "decimals": 0},
    "FSZK": {"chinese_name": "风蚀状况", "decimals": 0},
    "TRBCJG": {"chinese_name": "土壤表层结构", "decimals": 0},
    "KZLD": {"chinese_name": "荒漠化沙化可治理度", "decimals": 0},
    "ZLCS": {"chinese_name": "治理措施", "decimals": 0},
    "ZLCD": {"chinese_name": "治理程度", "decimals": 0},
    "BHXFFS": {"chinese_name": "保护修复方式", "decimals": 0},
    "MUYAN": {"chinese_name": "母岩", "decimals": 0},
    "SMHZK": {"chinese_name": "石漠化状况", "decimals": 0},
    "SMHCD": {"chinese_name": "石漠化程度", "decimals": 0},
    "SMHYBLX": {"chinese_name": "石漠化演变类型", "decimals": 0},
    "YRDM": {"chinese_name": "岩溶地貌", "decimals": 0},
    "GX_BJ": {"chinese_name": "更新标记", "decimals": 0},
    "DC_RY": {"chinese_name": "调查人员", "decimals": 0},
    "DC_RQ": {"chinese_name": "调查日期", "decimals": 0},
    "Shape_Length": {"chinese_name": "图形周长", "decimals": 4},
    "Shape_Area": {"chinese_name": "图形面积", "decimals": 4}
}

# =====================================================================
# 2. 自然语言文本语义底座 (LINCAO_CODE_DICT) - 基于 PDF 深度解析
# =====================================================================
LINCAO_CODE_DICT = {
    "DI_LEI": {
        "0301": "乔木林地", "0302": "竹林地", "030301": "国家特别规定灌木林地",
        "030302": "一般灌木林地", "030401": "疏林地", "030402": "未成林地",
        "030403": "苗圃地", "030404": "采伐迹地", "030405": "火烧迹地", "030406": "林业直服设施用地",
        "040101": "天然牧草地", "040201": "人工牧草地", "040301": "其他草地",
        "050101": "森林沼泽", "050201": "灌丛沼泽", "050301": "沼泽草地", "050401": "其他沼泽地",
        "050501": "沿海滩涂", "050601": "内陆滩涂", "050701": "红树林地",
        "0101": "水田", "0102": "水浇地", "0103": "旱地", "0201": "果园", "0202": "茶园",
        "1003": "盐田", "1701": "河流水面", "1704A": "养殖坑塘", "2306": "裸土地"
    },
    "ZBFGLX": {
        "1111": "针叶林", "1112": "阔叶林", "1113": "针阔混交林", "1210": "针叶型疏林",
        "1220": "阔叶型疏林", "1121": "乔木型红树林", "1131": "毛竹林", "1311": "干旱半干旱区特灌",
        "1320": "一般灌木林", "1410": "乔木未成林", "2100": "草本型", "2200": "灌草型", "3100": "水田作物型"
    },
    "LD_QS": {"10": "国有", "20": "集体"},
    "TDSYQS": {"1": "国有", "2": "集体", "3": "其他"},
    "LMQS": {"1": "国有", "2": "集体", "3": "个人", "9": "其他"},
    "LMSYQS": {"1": "国有", "2": "集体", "3": "个人", "9": "其他"},
    "QI_YUAN": {"11": "天然下种", "12": "萌生起源", "13": "人工促进天然更新", "21": "植苗造林", "22": "直播造林", "23": "飞播造林", "24": "人工林采伐后萌生"},
    "ZB_JG": {"1": "乔灌草型", "2": "乔灌型", "3": "乔草型", "4": "乔木型", "5": "灌草型", "6": "灌木型", "7": "草本型", "8": "作物型"},
    "LIN_ZHONG": {
        "111": "水源涵养林", "112": "水土保持林", "113": "防风固沙林", "121": "国防林",
        "125": "风景林", "127": "自然保护林", "231": "短轮伐期用材林", "233": "一般用材林",
        "241": "油料能源林", "251": "果树林", "254": "药用林"
    },
    "SHI_QUAN_D": {"10": "国家级公益林", "20": "地方公益林"},
    "LDGL_LX": {
        "10": "现状林地", "20": "现状占用按林地管理的土地", "21": "建设项目临时占用林地", 
        "23": "毁林开垦", "30": "其他按林地管理的土地", "31": "迹地", "32": "未成林造林地"
    },
    "BH_DJ": {"1": "I级保护林地", "2": "II级保护林地", "3": "III级保护林地", "4": "IV级保护林地"},
    "DI_MAO": {"1": "极高山", "2": "高山", "3": "中山", "4": "低山", "5": "丘陵", "6": "平原"},
    "PO_XIANG": {"1": "北坡", "2": "东北坡", "3": "东坡", "4": "东南坡", "5": "南坡", "6": "西南坡", "7": "西坡", "8": "西北坡", "9": "无坡向"},
    "PO_WEI": {"1": "脊部", "2": "上坡", "3": "中坡", "4": "下坡", "5": "谷地", "6": "平地"},
    "TU_RANG_ZD": {"1": "粘土", "2": "壤土", "3": "砂壤土", "4": "砂土", "5": "沙土"},
    "CY_FQ": {"1": "内蒙古高原草原区", "2": "西北山地盆地草原区", "3": "青藏高原草原区", "4": "东北华北平原山地丘陵草原区", "5": "南方山地丘陵草原区"},
    "CD_QY": {"1": "天然草原", "2": "人工草地"},
    "CDGN": {"1": "生态公益类草原", "2": "生产经营类草原", "3": "生活服务类草原", "4": "综合功能用途类草原"},
    "CDLYFS": {"11": "全年放牧", "14": "夏季放牧", "20": "打(割)草", "31": "自然保护", "34": "水源涵养"},
    "CYLB": {"1": "基本草原", "2": "非基本草原", "3": "未划定"},
    "JKDJ": {"1": "健康", "2": "亚健康", "3": "不健康", "4": "极不健康"},
    "THLX": {"1": "沙化", "2": "盐渍化", "3": "黑土滩退化", "4": "石漠化", "5": "毒害草型退化", "6": "鼠害退化"},
    "THCD": {"1": "未退化", "2": "轻度退化", "3": "中度退化", "4": "重度退化"},
    "JM_PH": {"1": "禁牧区", "2": "草畜平衡区"},
    "CDGL_LX": {"11": "现状草地", "12": "补充草地", "14": "毁草开垦", "21": "城镇村及工矿用地", "31": "已划入耕地保护红线"},
    "SD_DJ": {"1": "国际重要湿地", "2": "国家重要湿地", "3": "省级重要湿地", "4": "一般湿地"},
    "SDLYFS": {"01": "种植业", "02": "养殖业", "03": "牧业", "08": "旅游和休闲", "10": "未利用"},
    "SDWXZK": {"111": "水污染安全", "112": "水污染轻度", "211": "无围垦", "411": "人为水文干扰小"},
    "SDGLLX": {"11": "林业草原主管部门", "13": "水行政主管部门", "15": "农业农村主管部门", "20": "不按湿地管理"},
    "DCQLX": {"1": "荒漠化沙化调查区", "2": "荒漠化调查区", "3": "沙化调查区", "4": "石漠化调查区"},
    "QHLX": {"1": "极干旱区", "2": "干旱区", "3": "半干旱区", "4": "亚湿润干旱区", "5": "湿润区"},
    "HMHLX": {"1": "风蚀", "2": "水蚀", "3": "盐渍化", "4": "冻融", "9": "非荒漠化"},
    "HMHCD": {"1": "轻度", "2": "中度", "3": "重度", "4": "极重度"},
    "SHLX": {"110": "流动沙地(丘)", "120": "半固定沙地(丘)", "130": "固定沙地(丘)", "140": "沙化耕地", "160": "风蚀残丘(劣地)", "170": "戈壁(沙砾地)", "190": "具有明显沙化趋势的土地", "200": "非沙化土地"},
    "SHCD": {"1": "轻度", "2": "中度", "3": "重度", "4": "极重度"},
    "FSZK": {"1": "无风蚀", "2": "弱风蚀", "3": "中风蚀", "4": "强风蚀"},
    "TRBCJG": {"1": "形成腐殖质层", "2": "形成生物结皮层", "3": "两者均没有"},
    "KZLD": {"1": "难治理荒漠化、沙化土地", "2": "可治理荒漠化、沙化土地"},
    "ZLCS": {"101": "封山(沙)育林(草)", "102": "人工造林", "201": "保护性耕作", "301": "小型水利水保工程"},
    "ZLCD": {"1": "初步治理", "2": "中等治理", "3": "基本治理", "4": "沙转非", "5": "未达成效", "9": "无治理"},
    "SMHZK": {"1": "石漠化土地", "2": "潜在石漠化土地", "3": "非石漠化土地"},
    "SMHCD": {"1": "轻度(I)", "2": "中度(II)", "3": "重度(III)", "4": "极重度(IV)"},
    "SMHYBLX": {"1": "明显改善型", "2": "轻微改善型", "3": "稳定型", "4": "退化加剧型", "5": "退化严重加剧型"}
}